# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6099baa9c3205dccecb2a8119c4d36cff74744e1c5e8b62b72845796405e55d049c6f8884cbadbdfc9862e50457cd4d49da677b8d668fa4f928776318a34b651

test:
  secret_key_base: 49fd6d71c3a9ad760ca843bdf70e99a6023022dbb0dba2cbc688338711e5f313ffc4c9cf580eed2bc42514e7c79e5184d6a3df59c28a3e321a27f9cc339554f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
